---
title: "Model 1 analysis"
author: "Benjamin Mercier"
date: "`r paste('Last updated on', format(Sys.time(), '%d %B, %Y'))`"
---

<!-- Load nedeed libraries -->
```{r, echo = FALSE, message=FALSE, warning=FALSE}
suppressPackageStartupMessages(library(rstan))
suppressPackageStartupMessages(library(loo))
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(tidybayes))
suppressPackageStartupMessages(library(bayesplot))
suppressPackageStartupMessages(library(knitr))
suppressPackageStartupMessages(library(ggdist))
suppressPackageStartupMessages(library(ggridges))
suppressPackageStartupMessages(library(hrbrthemes))
suppressPackageStartupMessages(library(viridis))
suppressPackageStartupMessages(library(gridExtra))
suppressPackageStartupMessages(library(patchwork))
```
<!-- Load the data --> 
```{r load_model1, echo = FALSE, include = FALSE}
dataset <- readRDS("../data/clean/new_dataset.RDS")
output_stan_model1 <- readRDS("../results/model_outputs/output_stan_model1.RDS")
source("../R/10_plot_func.R")
```

# Model 1
## Description of the model
<br>
Model 1 fits the flux between a prey (i) and its predator (j) only based on mass-action (biomass of prey and abundance of predators).
The scaling parameters $\alpha$ is general to every predator.
<!-- Model equation -->
\begin{align}
F_{ij}^{real} &= \alpha * B_i * \frac{B_j}{M_j}
\end{align}

```{r structure_data, echo = FALSE}
# Recover types
output_stan_model1 <- recover_types(output_stan_model1)
# Draw the posterior for all parameters
general_params <- output_stan_model1 |>
                   tidybayes::gather_draws(a_pop, sigma)
```

## Summary table
```{r table_1, echo = FALSE}
kable(summary(output_stan_model1, pars = c("a_pop","sigma"))$summary, caption = "Summary table model 1")
```

```{r compute_loo, echo=FALSE, include=FALSE, warning=FALSE, message=FALSE, include=FALSE}
log_lik_1 <- extract_log_lik(output_stan_model1, merge_chains = FALSE)
r_eff_1 <- relative_eff(exp(log_lik_1))
loo_1 <- loo(log_lik_1, r_eff = r_eff_1, save_psis = TRUE)
```

## Posterior predictive checks
```{r wrangling_yrep, echo=FALSE, warning=FALSE, message=FALSE, include=FALSE}
yrep_1 <- rstan::extract(output_stan_model1, pars = "y_rep")[[1]]

dataset <- dataset |>
           dplyr::mutate(
            yrep_1_mean = apply(yrep_1, 2, mean)
           )
```

```{r ppc_plots, echo=FALSE, warning=FALSE, message=FALSE, include=FALSE}
# Plots for model 0
ppc_plot1 <- ppc_loo_pit_overlay(
  y = log(dataset$pred_flow),
  yrep = yrep_1,
  lw = weights(loo_1$psis_object)
) + labs(title = "Model 1")
qq_plot1 <- ppc_loo_pit_qq(
  y = log(dataset$pred_flow),
  yrep = yrep_1,
  lw = weights(loo_1$psis_object)
) + labs(title = "Model 1")
```

```{r plot_ppc_qq, echo=FALSE, warning=FALSE, message=FALSE}
ppc_plot1
qq_plot1
```

```{r ppc_dens, echo=FALSE, warning=FALSE, message=FALSE}
bayesplot::ppc_dens_overlay(log(dataset$pred_flow), yrep_1[1:500, ]) + labs(title = "Model 0")
```

## One-one plot of simulation against data
```{r one-one-plot, echo=FALSE, warning=FALSE, message=FALSE}
one_one_plot(dataset, 1) + xlim(c(-16,16)) + ylim(c(-16,16))
```

```{r sim_plot, echo=FALSE, warning=FALSE, message=FALSE, fig.width=15, fig.height=12}
plot_sim_noerror(output_stan_model1)
plot_sim_error(output_stan_model1)
```