---
output:
  xaringan::moon_reader:
  #  self_contained: TRUE
    includes:
      in_header: conf/style-header.html
    lib_dir: assets
    seal: false
    css: ["conf/css/style.css", "conf/css/fonts.css"]
    nature:
      beforeInit: "conf/style-macros.js"
---

```{r setup, echo = F}
knitr::opts_chunk$set(
  comment = "#",
  #cache = TRUE,
  collapse = TRUE,
  warning = FALSE,
  message = FALSE,
  fig.width = 7,
  fig.height = 5.25,
  fig.align = 'center'
)
mypar = list(mar = c(3,3,0.5,0.5), mgp = c(1.5, 0.3, 0), tck = -.008)
```

class: middle, title-slide

# Prediction of interaction strength within trophic networks of interactions

## Research committee reunion <br> BIO700

<br><br><br><br><br><br><br>

### Benjamin Mercier, <br> .small[Master student in ecology]

---

class:
# In context

 1. Climate change is affecting biodiversity in all its forms, including species interaction .tiny[(Estes et al. (2011), Lurgi et al. (2012), Purves et al. (2013))]
<br><br>
 2. Why is inference/prediction of interaction strength important?<br>
  a. Community dynamics .tiny[(Paine (1988), and many others)]<br><br>
  b. Community stability .tiny[(Neutel (2002), Ruiter et al. (1995))]<br><br>
  c. Ecosystem functionning and services .tiny[(Duffy (2002), Montoya et al. (2003))]<br><br>

---

# In context

- Prediciton of network topology has been done quite a lot in contrast to interaction strength <br><br>

## Still it has been done:
1. Lotka-Volterra framework with predator-prey body mass .tiny[Yodzis & Innes (1992), Pawar (2015),Emmerson & Raffaelli (2004)]
2. Metabolic rates .tiny[(Berlow et al. (2009))]
3. Foraging theory .tiny[(Brose et al. (2010))]

---

# In context

- We also know that interaction depends on local trait distribution and abundances .tiny[(Poisot et al. (2015))]
<br><br><br>
.center[**Need a more mechanistic understanding of the distribution of interaction strength as energy fluxes in networks**]

---

# Prediction of interaction strength based on traits

  1. Body mass
  2. Body size
  2. Metabolic theory (metabolic rates, metabolism type)
  3. Foraging theory (Movemetn capacity, detection capacity)
  4. Abundances and biomass

---

# Objectives
### Project objective
- Develop a mechanistic model that accurately explains the distribution of energy fluxes within trophic networks and validate it with empirically sampled quantiative networks
- If the data allows it: explore how the distribution of energy fluxes vary agmonst different ecosystem/spatially
<br><br>

### Personal objective
- Being able to develop/construct a model, and better understanding of statistics in general
---

# Methodology
- Model we will use are not yet defined.
<br><br>
- Compare mechanistic model to a phenomenological one (Random Forest)
<br><br>
- Use a more "black-box approach" like machine learning / likelyhood to understand which variable explains the distribution of energy fluxes
<br><br>
- Need to find quantitative trophic food webs with energy fluxes, abundance or biomass and the more traits available the better

---

# Questions

- Prediction of pairwise interaction and then build network, or prediction on the distribution of interaction strength on the whole network?
<br><br>
- Are there important parameters/elements that we need to think of in a model like that?
<br><br>
- Do we think of other characteristics the dataset should meet?

---

# Questions
- Which other traits could be included?
<br><br>
- Is there a way to diminish the effect of working with averaged measure of traits to the whole species?
<br><br>
- Is there a way to include the effect of the environment (maybe a stochastic way?)?

---
#

# Questions-
- Would there be a different approach to predict the distribution of energy fluxes in trophic networks?
<br><br>
- Consider seasonality? How?